run-name: Terraform Deployment 

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws
     
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: AWS Configure
      run: aws configure set aws_access_key_id={{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key={{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region={{ secrets.AWS_REGION }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform validate
      run: terraform validate  
    - name: Terraform Plan
      run: terraform plan  
    - name: Terraform Apply
      run: terraform apply
    - name: Terraform Destroy
      run: terraform destroy   
      
