name: Terraform Workflow with Plan, Apply, PR Approval, and Destroy Stages

on:
  push:
    branches:
      - main

  workflow_dispatch: # Allows manual trigger for destroy step

jobs:
  # Stage 1: Terraform Plan
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Save Plan Artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

 # Stage 2: Terraform Apply
  apply:
    runs-on: ubuntu-latest
    needs: plan
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      run: |
         echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
         echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
         echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
  
    - name: Terraform Init 
      run: terraform init
  
    - name: Terraform Plan
      run: terraform plan -out=tfplan 
    
    - name: Save plan artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan


  # Stage 3: Create Pull Request  
  pull-request:
    runs-on: ubuntu-latest
    needs: apply
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        branch: main
        base: feature/terraform-destroy
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Add Terraform Destroy"
        body: "This PR adds the necessary Terraform destroy stage."
       


  # Stage 4: Terraform Destroy (After PR Approval)
  destroy:
    runs-on: ubuntu-latest
    needs: pull-request
    if: github.event.inputs.approval == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy --auto-approve

      - name: Terraform Destroy
        run: terraform destroy --auto-approve

